apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/crds?timeout=900s&ref=v2.8.4
- github.com/argoproj/argo-cd/manifests/base?timeout=900s&ref=v2.8.4
- github.com/argoproj/argo-cd/manifests/cluster-rbac?timeout=900s&ref=v2.8.4

namespace: argocd