apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/envs/dev
    repoURL: https://github.com/Kiverling/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
