metadata:
  name: prod-dadosapp
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dadosapp/envs/prod
    repoURL: https://github.com/Kiverling/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
