apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-deployment.yaml
  - namespace.yaml
# secretGenerator:
# - name: mysql-pass
#   literals:
#   - password=YOUR_PASSWORD
namespace: prometheus
configMapGenerator:
  - name: config
    files:
      - prometheus.yml
