apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
    tier: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.traitor.ar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
  tls:
    - hosts:
        - prometheus.traitor.ar
      secretName: traitor-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: frontend
    spec:
      containers:
        - image: prom/prometheus
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          name: prometheus
          # env:
          #   - name: prometheus_DB_HOST
          #     value: prometheus-mysql
          #   - name: prometheus_DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-pass
          #         key: password
          #   - name: prometheus_DB_USER
          #     value: prometheus
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: config-storage
              mountPath: /etc/prometheus
      volumes:
        - name: config-storage
          configMap:
            name: config
