apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: argocd-cm
  namespace: argocd
  behavior: merge
  literals:
  - accounts.tordek=apiKey, login
  - accounts.tordek.enabled=true