apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingressdadosapp.yaml
  - adminer.yaml
  - namespace.yaml
  - configmap.yaml
  - ../../base
namespace: dadosapp
patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: dadosapp
