apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadosapp
spec:
  selector:
    matchLabels:
      app: dadosapp
  template:
    metadata:
      labels:
        app: dadosapp
    spec:
      containers:
        - name: dadosapp
          image: ghcr.io/kiverling/dados_app:sha256-93b1d6f6138760f97b6464aaf2281084a1aa6e5b8d9ca63e4f1a71071e656f7b.sig
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: "MESSAGE"
              valueFrom:
                configMapKeyRef:
                  name: dadosapp
                  key: MESSAGE

          envFrom:
            - configMapRef:
                name: dadosapp
          startupProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 50
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 6
            periodSeconds: 6
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dadosapp
spec:
  selector:
    app: dadosapp
  type: ClusterIP
  ports:
    - port: 5000
