apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadosapp
spec:
  selector:
    matchLabels:
      app: dadosapp
  template:
    metadata:
      labels:
        app: dadosapp
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: dadosapp
          image: ghcr.io/kiverling/dados_app:v1.0.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: dadosapp
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 50
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 6
            periodSeconds: 6
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dadosapp
spec:
  selector:
    app: dadosapp
  type: ClusterIP
  ports:
    - port: 3000
