apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: dadosapp
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
      env: dev
  template:
    metadata:
      labels:
        app: adminer
        env: dev
    spec:
      containers:
      - name: adminer
        image: dockage/adminer:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pasword"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
      app: adminer
      env: dev
  type : NodePort
  ports:
  - port: 80
    nodePort: 30060