apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: dadosapp
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
      env: dev
  template:
    metadata:
      labels:
        app: adminer
        env: dev
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pasword"
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  selector:
      app: adminer
      env: dev
  type : LoadBalancer
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traitor-ingress
spec:
  rules:
  - host: adminer.traitor.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer
            port:
              number: 8080