apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadosapp
spec:
  selector:
    matchLabels:
      app: dadosapp
  template:
    metadata:
      labels:
        app: dadosapp
    spec:
      containers:
      - name: dadosapp
        image: kiverling/dadosapp
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: dadosapp
        startupProbe:
          httpGet:
              path: /
              port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 50
        livenessProbe:
          httpGet:
              path: /
              port: 5000
          initialDelaySeconds: 6
          periodSeconds: 6
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dadosapp
spec:
  selector:
    app: dadosapp
  type : NodePort
  ports:
  - port: 5000
    nodePort: 30050

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dadosapp
data:
  MESSAGE: Mi Primera Chamba
