apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
  namespace: dadosapp
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      env: dev
  template:
    metadata:
      labels:
        app: db
        env: dev
    spec:
      containers:
      - name: db-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pasword"