apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - mysql-deployment.yaml
 - wordpress-deployment.yaml
 - namespace.yaml
secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD
namespace: wordpress-dev